# Generated by Django 5.2.6 on 2025-10-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
    ]
