# Generated by Django 5.0 on 2025-11-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='location',
            field=models.CharField(blank=True, help_text='Location text (city)', max_length=200),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='projects',
            field=models.TextField(blank=True, help_text='Project keyword(s), comma-separated'),
        ),
    ]
