# Generated by Django 4.2.24 on 2025-10-24 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_application_job'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
